In [2]:
import numpy as np

In [3]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])


In [4]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [5]:
B.shape

(2, 2, 3)

In [6]:
B.ndim

3

In [7]:
B.size

12

In [8]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4]
    ]
])

/tmp/ipykernel_28226/1156286633.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [9]:
C.dtype

dtype('O')

In [10]:
C.shape

(2,)

In [11]:
C.size

2

# Indexing and Slicing of Matrices

In [12]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
A[1]

array([4, 5, 6])

In [14]:
A[1][0]

4

In [15]:
A[1, 0]

4

In [16]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [19]:
A[:2, 2:]

array([[3],
       [6]])

# Summary Statistics

In [21]:
a = np.array([1, 2, 3, 4])

In [22]:
a.sum()

10

In [23]:
a.mean()

2.5

In [25]:
a.std()

1.118033988749895

In [26]:
a.var()

1.25

# Linear Algebra

In [28]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [29]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [30]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [31]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [32]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [33]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [34]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
163000000/175


931428.5714285715